blueprint:
  name: Change light when mode changes
  description:
    "Changes lights on mode change, with a random delay of 5 to 30 seconds
    to spread out the work load on the network if for example one would use this template
    multiple times.
    When mode is Away they are automatically shut off.
    This blueprint is built with a dependency off a list-helper named (input_select.modes)
    and the list items are the following five (Away, Morning, Day, Evening, Night).
    This helper is used by an automation to set Away if no family members or guests
    are at home. Blueprint for that can be found here https://github.com/ticstyle/HA-Day-modes/blob/main/day_modes.yaml
    The other ones are set for different times of the day if anyone is home."
  domain: automation
  source_url: https://github.com/ticstyle/HA-Change-light-when-mode-changes/blob/main/change_light_when_mode_changes.yaml

  input:
    light_target:
      name: Light(s)
      default: {}
      selector:
        target:
          entity:
            - domain:
                - light

    mode:
      name: Mode entity
      description: For example a input select helper
      default: input_select.modes
      selector:
        entity:
          domain: input_select

    sleep_in_sensor:
      name: Sleep in Sensor
      description: For example a boolean helper
      default: input_boolean.sleep_in
      selector:
        entity:
          domain: input_boolean

    # -----------------------
    # Optional switch control
    # -----------------------
    control_switches:
      name: Control switches
      description: Enable switch control in this automation
      default: false
      selector:
        boolean: {}

    switch_target:
      name: Switch(es)
      default: {}
      selector:
        target:
          entity:
            - domain:
                - switch

    morning_switch_on:
      name: Morning – switches ON?
      default: true
      selector:
        boolean: {}

    day_switch_on:
      name: Day – switches ON?
      default: true
      selector:
        boolean: {}

    evening_switch_on:
      name: Evening – switches ON?
      default: true
      selector:
        boolean: {}

    night_switch_on:
      name: Night – switches ON?
      default: false
      selector:
        boolean: {}

    away_switch_on:
      name: Away – switches ON?
      default: false
      selector:
        boolean: {}

    # -----------------------
    # Lights (original)
    # -----------------------
    morning_toggle:
      name: Use morning (effects both lights and switches)
      selector:
        boolean: {}
      default: true

    morning_brightness:
      name: Morning Brightness
      description: 0-100%.
      default: 10
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: slider

    day_toggle:
      name: Use day (effects both lights and switches)
      selector:
        boolean: {}
      default: true

    day_brightness:
      name: Day Brightness
      description: 0-100%.
      default: 75
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: slider

    evening_toggle:
      name: Use evening (effects both lights and switches)
      selector:
        boolean: {}
      default: true

    evening_brightness:
      name: Evening Brightness
      description: 0-100%.
      default: 35
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: slider

    night_toggle:
      name: Use night (effects both lights and switches)
      selector:
        boolean: {}
      default: true

    night_brightness:
      name: Night Brightness
      description: 0-100%.
      default: 0
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: slider

    away_toggle:
      name: Use away (effects both lights and switches)
      selector:
        boolean: {}
      default: true

trigger:
  - platform: state
    entity_id: !input mode
    for:
      hours: 0
      minutes: 0
      seconds: 5

mode: restart
max_exceeded: silent

condition: []

action:
  # The delay
  - delay:
      seconds: "{{ range(5, 31) | random | int }}"

  - variables:
      do_switches: !input control_switches
      sw_morning: !input morning_switch_on
      sw_day: !input day_switch_on
      sw_evening: !input evening_switch_on
      sw_night: !input night_switch_on
      sw_away: !input away_switch_on
      # Make the Use morning/day/evening/night/away toggles control whole sequences
      morning_enabled: !input morning_toggle
      day_enabled: !input day_toggle
      evening_enabled: !input evening_toggle
      night_enabled: !input night_toggle
      away_enabled: !input away_toggle

  - choose:

      # Morning
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: !input mode
                state: Morning
              - condition: state
                entity_id: !input sleep_in_sensor
                state: "off"
        sequence:
          - condition: template
            value_template: "{{ morning_enabled }}"
          - service: light.turn_on
            enabled: !input morning_toggle
            data:
              brightness_pct: !input morning_brightness
            target: !input light_target
          # Switches (optional)
          - if:
              - condition: template
                value_template: "{{ do_switches }}"
            then:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ sw_morning }}"
                    sequence:
                      - service: switch.turn_on
                        target: !input switch_target
                default:
                  - service: switch.turn_off
                    target: !input switch_target

      # Day
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: !input mode
                state: Day
        sequence:
          - condition: template
            value_template: "{{ day_enabled }}"
          - service: light.turn_on
            enabled: !input day_toggle
            data:
              brightness_pct: !input day_brightness
            target: !input light_target
          # Switches (optional)
          - if:
              - condition: template
                value_template: "{{ do_switches }}"
            then:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ sw_day }}"
                    sequence:
                      - service: switch.turn_on
                        target: !input switch_target
                default:
                  - service: switch.turn_off
                    target: !input switch_target

      # Evening
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: !input mode
                state: Evening
        sequence:
          - condition: template
            value_template: "{{ evening_enabled }}"
          - service: light.turn_on
            enabled: !input evening_toggle
            data:
              brightness_pct: !input evening_brightness
            target: !input light_target
          # Switches (optional)
          - if:
              - condition: template
                value_template: "{{ do_switches }}"
            then:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ sw_evening }}"
                    sequence:
                      - service: switch.turn_on
                        target: !input switch_target
                default:
                  - service: switch.turn_off
                    target: !input switch_target

      # Night
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: !input mode
                state: Night
        sequence:
          - condition: template
            value_template: "{{ night_enabled }}"
          - service: light.turn_on
            enabled: !input night_toggle
            data:
              brightness_pct: !input night_brightness
            target: !input light_target
          # Switches (optional)
          - if:
              - condition: template
                value_template: "{{ do_switches }}"
            then:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ sw_night }}"
                    sequence:
                      - service: switch.turn_on
                        target: !input switch_target
                default:
                  - service: switch.turn_off
                    target: !input switch_target

      # Away
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: !input mode
                state: Away
        sequence:
          - condition: template
            value_template: "{{ away_enabled }}"
          - service: light.turn_off
            data: {}
            target: !input light_target
            enabled: !input away_toggle
          # Switches (optional)
          - if:
              - condition: template
                value_template: "{{ do_switches }}"
            then:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ sw_away }}"
                    sequence:
                      - service: switch.turn_on
                        target: !input switch_target
                default:
                  - service: switch.turn_off
