blueprint:
  name: Change light when mode changes
  description:
    Changes lights on mode change, with a random delay of 5 to 30 seconds to spread out the work load on the network .
    When mode is Away they are automatically shut off.
    This blueprint is built with a dependency off a lis-helper named (input_select.modes) and the list items are the following five
    (Away, Morning, Day, Evening, Night).
    This helper is used by an automation to set Away if no family members or guests are at home.
    The other ones are set for different times of the day if anyone is home.
    We also need a boolean helper sensor (input_boolean.sleep_in) that you can set to on if you want to sleep in, if that sensor is (On) the (Morning) modes is ignored.
  domain: automation
  source_url: https://gist.github.com/ticstyle/f5f7409f5b9259f60bdeb5a3346666e9
  input:
    light_target:
      name: Light(s)
      selector:
        target:
          entity:
            domain: light
    #sleep_in_sensor:
    #  name: Sleep in Sensor
    #  description: For example a boolean helper
    #  selector:
    #    target:
    #      entity:
    #        domain: input_boolean
    morning_toggle:
      name: Use morning
      selector:
        boolean: {}
      default: true
    morning_brightness:
      name: Morning Brightness
      description: 0-100%.
      default: 10
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: slider
    day_toggle:
      name: Use day
      selector:
        boolean: {}
      default: true
    day_brightness:
      name: Day Brightness
      description: 0-100%.
      default: 75
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: slider
    evening_toggle:
      name: Use evening
      selector:
        boolean: {}
      default: true
    evening_brightness:
      name: Evening Brightness
      description: 0-100%.
      default: 35
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: slider
    night_toggle:
      name: Use night
      selector:
        boolean: {}
      default: true
    night_brightness:
      name: Night Brightness
      description: 0-100%.
      default: 0
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: slider
variables:
  morning_toggle: !input morning_toggle
  day_toggle: !input day_toggle
  evening_toggle: !input evening_toggle
  night_toggle: !input night_toggle
trigger:
  - platform: state
    entity_id:
      - input_select.modes
    for:
      hours: 0
      minutes: 0
      seconds: 5
mode: restart
max_exceeded: silent
condition: []
action:
  - delay:
      seconds: "{{ range(5, 30)|random|int }}"
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: input_select.modes
                state: Morning
              - condition: state
                entity_id: input_boolean.sleep_in
                state: "off"
              - condition: state
                entity_id: !input morning_toggle
                state: true
        sequence:
          service: light.turn_on
          data:
            brightness_pct: !input morning_brightness
          target: !input light_target
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: input_select.modes
                state: Day
              - condition: state
                entity_id: !input day_toggle
                state: true
        sequence:
          service: light.turn_on
          data:
            brightness_pct: !input day_brightness
          target: !input light_target
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: input_select.modes
                state: Evening
              - condition: state
                entity_id: !input evening_toggle
                state: true
        sequence:
          service: light.turn_on
          data:
            brightness_pct: !input evening_brightness
          target: !input light_target
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: input_select.modes
                state: Night
              - condition: state
                entity_id: !input night_toggle
                state: true
        sequence:
          service: light.turn_on
          data:
            brightness_pct: !input night_brightness
          target: !input light_target
      - conditions:
          condition: state
          entity_id: input_select.modes
          state: Away
        sequence:
          service: light.turn_off
          data: {}
          target: !input light_target